# Generated by Django 3.2.13 on 2022-09-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_rename_name_email_subscription_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Username', models.CharField(max_length=200)),
                ('Age', models.IntegerField(default=0)),
                ('Description', models.TextField()),
            ],
        ),
    ]
