# Generated by Django 3.2.13 on 2022-09-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='prefetch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
            ],
        ),
    ]
